# @package _global_

# default evaluate setup
# other evaluate configs can inherit from this one

# overwrite task name so debugging logs are stored in separate folder
task_name: "evaluate_other"

# disable callbacks and loggers during debugging
callbacks: null

train: False

test: False 

mode: "evaluate"
eval_otherprog_with_psroadv: true


evaluate_adv_dir: /home/yuheng/acces_games/logs/train_ccdo/runs/acsp50/am-acsp50/2024-09-22_20-10-26
adv_npz_pth: ${evaluate_adv_dir}/ccdo/info.npz
ckpt_psro_path: ${evaluate_adv_dir}

## eval rl
eval_rl_prog: false
# rl
rl_prog_dir: /home/yuheng/acces_games/logs/train/runs/acsp50/am-acsp50/2024-09-22_19-57-54
rl_prog_pth: ${rl_prog_dir}/rl4co/c1b28edi/checkpoints/epoch=0-step=20.ckpt

## eval baseline
eval_baseline_prog: true
baseline_heur: "LS2"   # "tabu" for acvrp; "LS2" or acsp, "greedy_op" for pg


